version: '3.9'

services:

  backend:

    build: .

    container_name: sentinelops-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    restart: always

    db:
    image: postgres:15

    container_name: sentinelops-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinelops

      ports:
        - "5432:5432"

      volumes:
         - postgres_data:/var/lib/postgresql/data

          restart: always

  volumes:
    postgres_data: